### ISSUE TITLE
Dispatch encoding problem 

### ISSUE THREAD

**Issue by bcambel** [gf3/secretary#72]
When dispatch method receives a URL like 

```page-visits/path=%2F60645%2Fzon-en-zee-strandhotel-westende%2F/day=2015-08-19%7C2015-08-19  ``` 

```clj
;; this is the route
(defroute "/:module/*" {:as params}
  (move-to params))
```
the route is called with the following parameters

```clj
{:module "page-visits" 
  :* "path=/60645/zon-en-zee-strandhotel-westende//day=2015-08-19|2015-08-19"
```

Is this an expected behaviour ? Could it be because of this https://github.com/gf3/secretary/blob/fc8b53e77604e87db82a68aec0e4e98fe3ba6fb8/src/secretary/core.cljs#L250

Cheers,
Bahadir

**Comment by noprompt** [comment]
@bcambel That appears correct to me. Could you explain what the problem is and/or what you expect the result to be in this case?

**Comment by bcambel** [comment]
My naming is misleading; 
the path in this context is actually a filter applied to the current context of the analytical tool.

What I am trying to achieve like Query Strings; but it's more readable by end users.
```path ``` = ```%2F60645%2Fzon-en-zee-strandhotel-westende%2F```
```day``` = ``` 2015-08-19%7C2015-08-19 ```
```utm_source``` = ```value```
and goes on..

The problem is that catch all returns me the complete decoded path, which means I lose which part is dimension which part is value.

**Comment by joelash** [comment]
@bcambel I assumed that's what you were going for and I believe the issue is your route, you're missing the `?` that usually signifies query params and you're missing the `&` between params. The general format of a URL is `/path?param1=value1&param2=value2`

 Try the `defroute` with `/page-visits/?path=%2F60645%2Fzon-en-zee-strandhotel-westende%2F&day=2015-08-19%7C2015-08-19` as your route.

Example:

```clojurescript
cljs.user=> (secretary/dispatch! "/page-visits/?path=%2F60645%2Fzon-en-zee-strandhotel-westende%2F&day=2015-08-19%7C2015-08-19")
;{:modules page-visits, :* , :query-params {:path /60645/zon-en-zee-strandhotel-westende/, :day 2015-08-19|2015-08-19}}
```

After seeing this, perhaps what you're really looking for as your `defroute` is something as simple as.

```clojure
(defroute "/:module" {:as params}
   ....)
```

**Comment by bcambel** [comment]
hey @joelash thanks. I followed your suggestion and replaced the solution with query parameters.
